DROP TABLE WIKI_PAGE IF EXISTS;

CREATE TABLE WIKI_PAGE (
   NAME VARCHAR(100) PRIMARY KEY,
   CONTENT VARCHAR(200),
   UPDATE_TIME TIMESTAMP  DEFAULT CURRENT_TIMESTAMP
);




INSERT INTO WIKI_PAGE(NAME, CONTENT) VALUES('welcome', 'ようこそ PuchiWikiへ

Wikiは誰もが書き込めるWeb上の
コラボレーションツールらしいです。');
INSERT INTO WIKI_PAGE(NAME, CONTENT) VALUES('てすと', 'てすと');
INSERT INTO WIKI_PAGE(NAME, CONTENT) VALUES('てすと２', 'てすと');
INSERT INTO WIKI_PAGE(NAME, CONTENT) VALUES('フォーマット', 'フォーマットのテスト
リンク http://google.com/ 
タグ <>
タブ [	]
');


INSERT INTO WIKI_PAGE(NAME, CONTENT, UPDATE_TIME) VALUES('サーブレット', 'あああ',  '2010-02-05 00:00:00');
INSERT INTO WIKI_PAGE(NAME, CONTENT, UPDATE_TIME) VALUES('JSF', 'あああ',  '2010-02-04 00:00:00');
INSERT INTO WIKI_PAGE(NAME, CONTENT, UPDATE_TIME) VALUES('Annotation', 'あああ',  '2010-02-03 00:00:00');
INSERT INTO WIKI_PAGE(NAME, CONTENT, UPDATE_TIME) VALUES('ResultSet', 'あああ',  '2010-02-02 00:00:00');
INSERT INTO WIKI_PAGE(NAME, CONTENT, UPDATE_TIME) VALUES('Java', 'あああ',  '2010-02-01 00:00:00');

