DROP TABLE ACCOUNT IF EXISTS;

CREATE TABLE ACCOUNT (
  ID INTEGER PRIMARY KEY,
  NAME VARCHAR(100),
  MONEY INTEGER
);

INSERT INTO ACCOUNT(ID, NAME, MONEY) VALUES(1, 'ボブ',       1000);
INSERT INTO ACCOUNT(ID, NAME, MONEY) VALUES(2, 'パトリック', 2000);
INSERT INTO ACCOUNT(ID, NAME, MONEY) VALUES(3, 'サンディー', 3000);

SELECT * FROM ACCOUNT
